on:
  push:
    branches:
      - master
env:
  BUN_VERSION: 1.2.21
  ZIG_VERSION: 0.15.1
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-zig
          path: zig-cache
      - run: zig build test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-zig
          path: zig-cache
      - run: zig build -Doptimize=ReleaseSmall -p _site
      - uses: actions/upload-pages-artifact@v4
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
