on:
  push:
    branches:
      - master
env:
  BUN_VERSION: 1.0.21
  ZIG_VERSION: 0.12.0-dev.2075+f5978181e
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}
      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-zig
          path: zig-cache
      - run: zig build test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}
      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-zig
          path: zig-cache
      - run: zig build -Doptimize=ReleaseSmall -p _site
      - uses: actions/upload-pages-artifact@v3
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
