name: Github Pages
on:
  push:
    branches:
      - master
jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0-dev.1460+e675af069
      - run: zig build-lib -OReleaseSmall zig/main.zig -target wasm32-freestanding -dynamic --export=setup --export=update
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          exclude_assets: .github,.gitignore,zig,zig-cache
    permissions:
      contents: write
